name: CI
on:
  release:
    types: [published]
  pull_request:
  push:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Tag from SHA
        shell: bash
        if:  "${{ github.event_name != 'release' }}"
        run: echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Get Tag from Release
        shell: bash
        if: "${{ github.event_name == 'release' }}"
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Check Image exists in repo
        shell: bash
        run: |
          set +e
          IMAGES=$(docker compose convert --images)
          echo "Tag = ${TAG}"
          for IMG in $IMAGES
          do
            echo "Checking: ${IMG}"
            docker manifest inspect $IMG > /dev/null;
            if [[ $? -eq 0 ]]; then
              echo "Error: already exists: ${IMG}"
              exit 1
            fi
            echo "Ok: image does not exist: ${IMG}"
          done
      
      - name: Build Image
        shell: bash
        run: |
          docker buildx create --use
          bash .github/compose.sh build dev

      - name: Run Checks
        shell: bash
        run: docker compose run --entrypoint=just dev ci

      # Need to set tag in docker-compose.yaml and uncomment to get image build
      # Also need to set these secrets in github
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Image
      #   shell: bash
      #   if: "startsWith(github.ref, 'refs/tags/')"
      #   run: docker compose push

      # Need to change default permissions of gh-actions-bot for this to work
      - name: Deploy Documentation
        shell: bash
        if: "startsWith(github.ref, 'refs/tags/')"
        run: bash .github/compose.sh run dev mkdocs gh-deploy --force -v