site_name: {{ cookiecutter.project_slug }}
nav:
  - Home: index.md
  - Examples: example.ipynb
theme:
  name: material
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'


plugins:
  - mkdocs-jupyter